[project]
name = "nextnode-front"
description = "NextNode Solutions website"
domain = "nextnode.fr"

[environments.development]
enabled = true
server = "dev-worker"

[environments.preview]
enabled = true
server = "dev-worker"

[environments.production]
enabled = true
server = "prod-worker"
memory = "512M"
cpu = "0.5"
